services:
  wacalls:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - DATABASE_URL=postgresql://brandall:Hansol1974%2B@basededato-6cfbai:5432/wacall2?sslmode=disable
